#! python3

import os, csv  # install these modules if necessary

excelFile = open("C:\\Users\\Rozh\\Desktop\\Document_Folders_List.csv", 'w', newline='', encoding='utf-8')  # creates a new .csv file at a location of your choice (modify the path to whatever you desire)

write = csv.writer(excelFile, quoting = csv.QUOTE_ALL)  # allows writing to .csv file

for f in sorted(os.listdir("C:\\Users\\Rozh\\OneDrive\\Documents")):  # parent directory from which you wish to read files & folders
    print(f)
    write.writerow([f])  # writes a single row per folder or file present in the parent directory
